import type { SourceSpan } from "../diagnostics/diagnostic.js";

export enum TokenKind {
  Identifier = "Identifier",
  String = "String",
  Char = "Char",
  /** Full template with no interpolations: `hello` */
  TemplateNoSub = "TemplateNoSub",
  /** Template prefix ending at `${`: `hello ${ */
  TemplateHead = "TemplateHead",
  /** Template middle between `}` and `${`: }world ${ */
  TemplateMiddle = "TemplateMiddle",
  /** Template suffix after final `}`: }!` */
  TemplateTail = "TemplateTail",
  Integer = "Integer",
  Float = "Float",

  Function = "function",
  Struct = "struct",
  Enum = "enum",
  Class = "class",
  Interface = "interface",
  Type = "type",
  This = "this",
  New = "new",
  Extends = "extends",
  Implements = "implements",
  Super = "super",
  Abstract = "abstract",
  Public = "public",
  Private = "private",
  Readonly = "readonly",
  Static = "static",
  Constructor = "constructor",
  Import = "import",
  Export = "export",
  Extern = "extern",
  From = "from",
  As = "as",
  Let = "let",
  Const = "const",
  Return = "return",
  True = "true",
  False = "false",
  If = "if",
  Else = "else",
  ElseIf = "elseif",
  While = "while",
  For = "for",
  Break = "break",
  Continue = "continue",
  Switch = "switch",
  Case = "case",
  Default = "default",
  Throw = "throw",
  Try = "try",
  Catch = "catch",
  Finally = "finally",
  In = "in",
  Keyof = "keyof",
  Typeof = "typeof",
  Null = "null",
  Is = "is",
  Async = "async",
  Await = "await",
  Unsafe = "unsafe",

  At = "@",
  LParen = "(",
  RParen = ")",
  LBrace = "{",
  RBrace = "}",
  LBracket = "[",
  RBracket = "]",
  Semicolon = ";",
  Colon = ":",
  Comma = ",",
  Dot = ".",
  Plus = "+",
  PlusPlus = "++",
  PlusEqual = "+=",
  Minus = "-",
  MinusMinus = "--",
  MinusEqual = "-=",
  Star = "*",
  Slash = "/",
  Percent = "%",
  Equal = "=",
  EqualEqual = "==",
  Arrow = "=>",
  Bang = "!",
  BangEqual = "!=",
  Less = "<",
  LessEqual = "<=",
  Greater = ">",
  GreaterEqual = ">=",
  Amp = "&",
  AmpAmp = "&&",
  Pipe = "|",
  PipePipe = "||",
  Question = "?",
  QuestionQuestion = "??",
  QuestionDot = "?.",

  Eof = "Eof",
  Invalid = "Invalid",
}

export interface Token {
  readonly kind: TokenKind;
  readonly lexeme: string;
  /** Decoded value for string/char literals; otherwise undefined. */
  readonly value?: string;
  readonly span: SourceSpan;
}

export const KEYWORDS: ReadonlyMap<string, TokenKind> = new Map([
  ["function", TokenKind.Function],
  ["struct", TokenKind.Struct],
  ["enum", TokenKind.Enum],
  ["class", TokenKind.Class],
  ["interface", TokenKind.Interface],
  ["type", TokenKind.Type],
  ["this", TokenKind.This],
  ["new", TokenKind.New],
  ["extends", TokenKind.Extends],
  ["implements", TokenKind.Implements],
  ["super", TokenKind.Super],
  ["abstract", TokenKind.Abstract],
  ["public", TokenKind.Public],
  ["private", TokenKind.Private],
  ["readonly", TokenKind.Readonly],
  ["static", TokenKind.Static],
  ["constructor", TokenKind.Constructor],
  ["import", TokenKind.Import],
  ["export", TokenKind.Export],
  ["extern", TokenKind.Extern],
  ["from", TokenKind.From],
  ["as", TokenKind.As],
  ["let", TokenKind.Let],
  ["const", TokenKind.Const],
  ["return", TokenKind.Return],
  ["true", TokenKind.True],
  ["false", TokenKind.False],
  ["if", TokenKind.If],
  ["else", TokenKind.Else],
  ["elseif", TokenKind.ElseIf],
  ["while", TokenKind.While],
  ["for", TokenKind.For],
  ["break", TokenKind.Break],
  ["continue", TokenKind.Continue],
  ["switch", TokenKind.Switch],
  ["case", TokenKind.Case],
  ["default", TokenKind.Default],
  ["throw", TokenKind.Throw],
  ["try", TokenKind.Try],
  ["catch", TokenKind.Catch],
  ["finally", TokenKind.Finally],
  ["in", TokenKind.In],
  ["keyof", TokenKind.Keyof],
  ["typeof", TokenKind.Typeof],
  ["null", TokenKind.Null],
  ["is", TokenKind.Is],
  ["async", TokenKind.Async],
  ["await", TokenKind.Await],
  ["unsafe", TokenKind.Unsafe],
]);
