import type { SourceSpan } from "../diagnostics/diagnostic.js";

export enum TokenKind {
  Identifier = "Identifier",
  String = "String",
  Char = "Char",
  Integer = "Integer",
  Float = "Float",

  Function = "function",
  Struct = "struct",
  Enum = "enum",
  Class = "class",
  Interface = "interface",
  This = "this",
  New = "new",
  Extends = "extends",
  Implements = "implements",
  Super = "super",
  Abstract = "abstract",
  Public = "public",
  Private = "private",
  Readonly = "readonly",
  Static = "static",
  Constructor = "constructor",
  Import = "import",
  Export = "export",
  As = "as",
  Let = "let",
  Const = "const",
  Return = "return",
  True = "true",
  False = "false",
  If = "if",
  Else = "else",
  ElseIf = "elseif",
  While = "while",
  For = "for",
  Break = "break",
  Continue = "continue",
  In = "in",

  LParen = "(",
  RParen = ")",
  LBrace = "{",
  RBrace = "}",
  LBracket = "[",
  RBracket = "]",
  Semicolon = ";",
  Colon = ":",
  Comma = ",",
  Dot = ".",
  Plus = "+",
  PlusPlus = "++",
  PlusEqual = "+=",
  Minus = "-",
  MinusMinus = "--",
  MinusEqual = "-=",
  Star = "*",
  Slash = "/",
  Percent = "%",
  Equal = "=",
  EqualEqual = "==",
  Bang = "!",
  BangEqual = "!=",
  Less = "<",
  LessEqual = "<=",
  Greater = ">",
  GreaterEqual = ">=",
  AmpAmp = "&&",
  PipePipe = "||",

  Eof = "Eof",
  Invalid = "Invalid",
}

export interface Token {
  readonly kind: TokenKind;
  readonly lexeme: string;
  /** Decoded value for string/char literals; otherwise undefined. */
  readonly value?: string;
  readonly span: SourceSpan;
}

export const KEYWORDS: ReadonlyMap<string, TokenKind> = new Map([
  ["function", TokenKind.Function],
  ["struct", TokenKind.Struct],
  ["enum", TokenKind.Enum],
  ["class", TokenKind.Class],
  ["interface", TokenKind.Interface],
  ["this", TokenKind.This],
  ["new", TokenKind.New],
  ["extends", TokenKind.Extends],
  ["implements", TokenKind.Implements],
  ["super", TokenKind.Super],
  ["abstract", TokenKind.Abstract],
  ["public", TokenKind.Public],
  ["private", TokenKind.Private],
  ["readonly", TokenKind.Readonly],
  ["static", TokenKind.Static],
  ["constructor", TokenKind.Constructor],
  ["import", TokenKind.Import],
  ["export", TokenKind.Export],
  ["as", TokenKind.As],
  ["let", TokenKind.Let],
  ["const", TokenKind.Const],
  ["return", TokenKind.Return],
  ["true", TokenKind.True],
  ["false", TokenKind.False],
  ["if", TokenKind.If],
  ["else", TokenKind.Else],
  ["elseif", TokenKind.ElseIf],
  ["while", TokenKind.While],
  ["for", TokenKind.For],
  ["break", TokenKind.Break],
  ["continue", TokenKind.Continue],
  ["in", TokenKind.In],
]);
